name: Deploy Marketing Test Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v || echo "Tests completed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create environment file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > env
        echo "GOOGLE_SERVICE_ACCOUNT_FILE=${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILE }}" >> env
        echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> env
        echo "CONTEXT7_URL=${{ secrets.CONTEXT7_URL }}" >> env
        echo "GITHUB_REPO=https://github.com/synthosaicreativestudio-maker/test" >> env
    
    # Опция 1: Деплой на сервер через SSH
    - name: Deploy to server
      if: ${{ secrets.DEPLOY_HOST }}
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /path/to/your/project
          git pull origin main
          pip install -r requirements.txt
          sudo systemctl restart marketing-bot
          sudo systemctl restart marketing-web
    
    # Опция 2: Деплой на Heroku
    - name: Deploy to Heroku
      if: ${{ secrets.HEROKU_API_KEY }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
    
    # Опция 3: Деплой Docker контейнера
    - name: Build and push Docker image
      if: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/marketing-test:latest .
        docker push ${{ secrets.DOCKER_REGISTRY }}/marketing-test:latest